# .github/workflows/release.yml
name: Minimal CI Test

on:
  push:
    branches: [ main ]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello message
        run: echo "GitHub Actions is working!"